<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
  <el-form :model="budgetData" ref="BudgetInsert" :rules="rules" label-position="left" label-width="100px"
           size="default" @submit.prevent>
    <div class="card-container">
      <el-card style="{width: 100% !important}" shadow="always">
        <template #header>
          <div class="clear-fix">
            <span>经费申请</span>
          </div>
        </template>
        <el-row>
          <el-col :span="6" class="grid-cell">
            <el-form-item label="申请时间" prop="date22960" class="label-right-align">
              <el-date-picker v-model="budgetData.date22960" type="date" class="full-width-input"
                              format="YYYY-MM-DD" value-format="YYYY-MM-DD" clearable></el-date-picker>
            </el-form-item>
          </el-col>
          <el-col :span="8" class="grid-cell">
            <el-form-item label="经费申请名称" prop="input63122" class="label-right-align">
              <el-input v-model="budgetData.input63122" type="text" clearable></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="10" class="grid-cell">
            <el-form-item label="经费类别" prop="select58353" class="label-right-align">
              <el-select v-model="budgetData.select58353" class="full-width-input" clearable>
                <el-option v-for="(item, index) in select58353Options" :key="index" :label="item.value"
                           :value="item.value" :disabled="item.disabled"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="8" class="grid-cell">
            <el-form-item label="申请金额" prop="input40866" class="label-right-align">
              <el-input v-model="budgetData.input40866" type="text" placeholder="人民币（元）" clearable></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8" class="grid-cell">
            <el-form-item label="申请人工号" prop="input23041" class="label-right-align">
              <el-input v-model="budgetData.input23041" type="text" clearable></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8" class="grid-cell">
            <el-form-item label="所属部门" prop="select117504" class="label-right-align">
              <el-select v-model="budgetData.select117504" class="full-width-input" clearable>
                <el-option v-for="(item, index) in select117504Options" :key="index" :label="item.value"
                           :value="item.value" :disabled="item.disabled"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="24" class="grid-cell">
            <el-form-item label="申请理由" prop="textarea100243" class="label-right-align">
              <el-input type="textarea" v-model="budgetData.textarea100243" rows="3"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
      </el-card>
    </div>

    <br>

    <div class="card-container">
      <el-card style="{width: 100% !important}" shadow="never">
        <template #header>
          <div class="clear-fix">
            <span>申请资产明细</span>
            <i class="float-right el-icon-arrow-down"></i>
          </div>
        </template>
        <el-row>
          <el-col :span="12" class="grid-cell">
            <el-form-item label="资产编号" prop="input68189" class="label-right-align">
              <el-input v-model="budgetData.input68189" type="text" clearable></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="12" class="grid-cell">
            <el-form-item label="资产名称" prop="input80064" class="label-right-align">
              <el-input v-model="budgetData.input80064" type="text" clearable></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="12" class="grid-cell">
            <el-form-item label="资产型号" prop="input112947" class="label-right-align">
              <el-input v-model="budgetData.input112947" type="text" clearable></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="12" class="grid-cell">
            <el-form-item label="资产规格" prop="input83882" class="label-right-align">
              <el-input v-model="budgetData.input83882" type="text" clearable></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8" class="grid-cell">
            <el-form-item label="数量" prop="number22261" class="label-right-align">
              <el-input-number v-model="budgetData.number22261" class="full-width-input"
                               controls-position="right" :min="-100000000000" :max="100000000000" :precision="0" :step="1">
              </el-input-number>
            </el-form-item>
          </el-col>
          <el-col :span="8" class="grid-cell">
            <el-form-item label="计量单位" prop="input53729" class="label-right-align">
              <el-input v-model="budgetData.input53729" type="text" clearable></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8" class="grid-cell">
            <el-form-item label="单价" prop="input103413" class="label-right-align">
              <el-input v-model="budgetData.input103413" type="text" clearable></el-input>
            </el-form-item>
          </el-col>
        </el-row>
      </el-card>
    </div>
    <br>
    <div class="static-content-item" style="float: right">
      <el-button type="warning" plain>增加资产明细卡片</el-button>
      <el-button type="info" plain>保存申请</el-button>
      <el-button type="success" plain>提交申请</el-button>
    </div>
  </el-form>

</template>

<script>
import {
  defineComponent,
  toRefs,
  reactive,
  getCurrentInstance
}
  from 'vue'
export default defineComponent({
  components: {},
  props: {},
  setup() {
    const state = reactive({
      budgetData: {
        date22960: null,
        input63122: "",
        select58353: "2",
        input40866: "",
        input23041: "",
        select117504: 1,
        textarea100243: "",
        input68189: "",
        input80064: "",
        input112947: "",
        input83882: "",
        number22261: 0,
        input53729: "",
        input103413: "",
      },
      rules: {
        input40866: [{
          pattern: /^\d+(\.\d+)?$/,
          trigger: ['blur', 'change'],
          message: ''
        }],
        input23041: [{
          pattern: /^\d+(\.\d+)?$/,
          trigger: ['blur', 'change'],
          message: ''
        }],
      },
      select58353Options: [{
        "label": "科研",
        "value": 1
      }, {
        "label": "教学",
        "value": "2"
      }, {
        "label": "其他",
        "value": "3"
      }],
      select117504Options: [{
        "label": "部门1",
        "value": 1
      }, {
        "label": "部门2",
        "value": 2
      }, {
        "label": "部门3",
        "value": 3
      }],
    })
    const instance = getCurrentInstance()
    const submitForm = () => {
      instance.ctx.$refs['vForm'].validate(valid => {
        if (!valid) return
        //TODO: 提交表单
      })
    }
    const resetForm = () => {
      instance.ctx.$refs['vForm'].resetFields()
    }
    return {
      ...toRefs(state),
      submitForm,
      resetForm
    }
  }
})

</script>

<style lang="scss">
.el-input-number.full-width-input,
.el-cascader.full-width-input {
  width: 100% !important;
}

.el-form-item--medium {
  .el-radio {
    line-height: 36px !important;
  }

  .el-rate {
    margin-top: 8px;
  }
}

.el-form-item--small {
  .el-radio {
    line-height: 32px !important;
  }

  .el-rate {
    margin-top: 6px;
  }
}

.el-form-item--mini {
  .el-radio {
    line-height: 28px !important;
  }

  .el-rate {
    margin-top: 4px;
  }
}

.clear-fix:before,
.clear-fix:after {
  display: table;
  content: "";
}

.clear-fix:after {
  clear: both;
}

.float-right {
  float: right;
}

</style>

<style lang="scss" scoped>
div.table-container {
  table.table-layout {
    width: 100%;
    table-layout: fixed;
    border-collapse: collapse;

    td.table-cell {
      display: table-cell;
      height: 36px;
      border: 1px solid #e1e2e3;
    }
  }
}

div.tab-container {}

.label-left-align :deep(.el-form-item__label) {
  text-align: left;
}

.label-center-align :deep(.el-form-item__label) {
  text-align: center;
}

.label-right-align :deep(.el-form-item__label) {
  text-align: right;
}

.custom-label {}

.static-content-item {
  min-height: 20px;
  display: flex;
  align-items: center;

  :deep(.el-divider--horizontal) {
    margin: 0;
  }
}

</style>