spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://82.157.138.64:3306/test
      username: root
      password: 123456
mybatis-plus:
  global-config:
    db-config:
      id-type: auto # 也可以在User.java中，对private String id;添加注解@TableId(type=IdType.AUTO)
