# 开发环境
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://82.157.138.64:3306/test
      username: root
      password: 123456
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 80
logging:
  level:
    root: info