spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # fixme 创建表失败原因：
      #因为mysql使用schema标识库名而不是catalog，因此mysql会扫描所有的库来找表，如果其他库中有相同名称的表，activiti就以为找到了，本质上这个表在当前数据库中并不存在。
      #设置nullCatalogMeansCurrent=true，表示mysql默认当前数据库操作，在mysql-connector-java 5.xxx该参数默认为true，在6.xxx以上默认为false，因此需要设置nullCatalogMeansCurrent=true。
      url: jdbc:mysql://82.157.138.64:3306/activiti_springboot?nullCatalogMeansCurrent=true
      username: root
      password: 123456
  activiti:
    database-schema-update: true

    # 检测历史信息表是否存在，不存在则创建。（因为activiti7默认不生成历史信息表
    db-history-used: true

    # 记录历史信息等级：
    #   none：不保存任何内容，最高效
    #   activity：保存流程实例和流程行为
    #   audit：保存activity的内容+全部的流程任务及其属性。（默认值
    #   full：保存audit的数据+全部流程相关的细节，比如流程参数
    history-level: full

    # 校验resources文件夹下是否有流程文件
    check-process-definitions: true