language: python
sudo: false
cache: pip
python:
- 2.7
- 3.4
- 3.5
- 3.6
install:
- travis_retry pip install -U tox-travis twine wheel codecov
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: redapple
  password:
    secure: eU1QIkapN3l8gCeHO9Q+GcT4RqooNuWj8HAamlLY6wT21kcRnA9Ok1PduPK+UmWlblAkP7RNXa4IwTtCD53BeG9LG9y5Dp/PlyIStX5UdNKQdIiXR3RRtTGetV88pVS1e3pBoc5NnevaNrQ2kvoQiK+MYJaRoZdY4cg41mrBwcA=
  on:
    tags: true
    repo: scrapy/scrapyd-client
    condition: "$TRAVIS_PYTHON_VERSION == '3.6'"
